spring.application.name=graph-db-benchmark

server.port=${PORT:8080}

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

benchmark.iterations=100
benchmark.warmup=10
benchmark.concurrent-clients=10
benchmark.batch-size=10000

database.dataset=data/pokec_edges_sample_100k.csv



# =============================
# CognoDB (Required)
# =============================

cognodb.uri=${COGNODB_URI:}

cognodb.username=${COGNODB_USERNAME:}

cognodb.password=${COGNODB_PASSWORD:}



# =============================
# Neo4j (Optional)
# =============================

neo4j.uri=${NEO4J_URI:}

neo4j.username=${NEO4J_USERNAME:}

neo4j.password=${NEO4J_PASSWORD:}



# =============================
# Memgraph (Optional)
# =============================

memgraph.uri=${MEMGRAPH_URI:}

memgraph.username=${MEMGRAPH_USERNAME:}

memgraph.password=${MEMGRAPH_PASSWORD:}



# =============================
# FalkorDB (Optional)
# =============================

falkordb.uri=${FALKORDB_URI:}

falkordb.username=${FALKORDB_USERNAME:}

falkordb.password=${FALKORDB_PASSWORD:}